[package]
name = "qali"
version = "0.1.0"
edition = "2021"
authiors = ["contact@jettchen.me"]
license = "MIT"
description = "QALI: Quick ALIasing in the terminal"
readme = "README.md"
homepage = "https://github.com/JettChenT/qali"
repository = "https://github.com/JettChenT/qali"
keywords = ["cli", "productivity", "aliasing"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.2.17", features=["derive"]}
directories = "4.0"